### ISSUE TITLE
`repository.get_changes` Fails with `IndexError` for Certain Files Changed in Merge Commits

### ISSUE THREAD

**Issue by nuthanmunaiah** [samaritan/services#36]
# Description

In resolving #34, a regression bug was introduced which causes `repository.get_changes` to raise `IndexError`, the traceback for which is shown below.

```
Traceback (most recent call last):
  File "/home/nm6061/samaritan/services/.venv/lib/python3.7/site-packages/nameko/containers.py", line 392, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./repository/service.py", line 31, in get_changes
    changes = list(repository.get_changes(sha, path))
  File "./repository/repository.py", line 149, in get_changes
    yield from self._get_changes_for_sha_to_path(sha, path)
  File "./repository/repository.py", line 330, in _get_changes_for_sha_to_path
    for _, lines in parsers.GitLogParser.parse(ostream):
  File "./repository/parsers.py", line 23, in parse
    yield (snippet[0], snippet[2:])
IndexError: list index out of range
```

The root cause of the bug is the lack of output from the `git log` command that `get_changes(project, sha, path)` internally executes to get the changes to `path` in commit identified by `sha` in `project`. The bug is _isolated_ to changes contributed to a project as merge commits _only_. Furthermore, the bug is not reproducible when the `path` changed in the merge commit was resolved for a merge conflict. The peculiarity of the bug is demonstrated using two merge commits from the https://github.com/google/brotli.

## Demonstration

https://github.com/google/brotli/commit/d767ab9eb043a32159a2db21fe4dc2f4d1bf3741 merged in changes to four files with no merge conflict. In this case, `repository.get_changes` raises `IndexError` when attempting to get changes to a particular file changed in the merge commit.

```
>>> n.rpc.repository.get_changes('brotli', 'd767ab9eb043a32159a2db21fe4dc2f4d1bf3741', 'BUILD')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/nm6061/samaritan/services/.venv/lib/python3.7/site-packages/nameko/rpc.py", line 373, in __call__
    return reply.result()
  File "/home/nm6061/samaritan/services/.venv/lib/python3.7/site-packages/nameko/rpc.py", line 331, in result
    raise deserialize(error)
nameko.exceptions.RemoteError: IndexError list index out of range
```

https://github.com/google/brotli/commit/4219fece592059522a1c800b3b16804d543f477e merged in changes to one file with a merge conflict. In this case, `repository.get_changes` works as expected.

```
$ nameko shell
>>> n.rpc.repository.get_changes('brotli', '4219fece592059522a1c800b3b16804d543f477e', 'dec/port.h')
[{'commit': {'sha': '4219fece592059522a1c800b3b16804d543f477e', 'timestamp': 1476711879, 'author': {'email': 'eustas@google.com', 'name': 'Eugene Kliuchnikov'}}, 'changes': {'dec/port.h': {'type': 3, 'oids': {'before': 'b23757ee4ad833bce0c43da65794935e77e1d2ae', 'after': 'f6badf3d11bbb0fb3729532596b9073e01baed49'}}}}]
```

https://github.com/google/brotli/commit/0477473ba249ff440b2b731beaf3372c1bf86a7c merged in changes to two files (`enc/streams.cc` and `enc/streams.h`) resolving a merge conflict in one of the two files (`enc/streams.cc`). In this case, `repository.get_changes` works as expected for the file to which merge conflict resolution was applied but raises `IndexError` for the file with no merge conflicts.

```
$ nameko shell
>>> n.rpc.repository.get_changes('brotli', '0477473ba249ff440b2b731beaf3372c1bf86a7c', 'enc/streams.h')
[{'commit': {'sha': '0477473ba249ff440b2b731beaf3372c1bf86a7c', 'timestamp': 1443784935, 'author': {'email': 'szabadka@users.noreply.github.com', 'name': 'szabadka'}}, 'changes': {'enc/streams.h': {'type': 3, 'oids': {'before': '5f8ef2d1c1142e1a5a96c45b7c1ddb656340dd79', 'after': '4f0c8e7256155b7b9be9286f342a5b87ed20aa99'}}}}]
>>> n.rpc.repository.get_changes('brotli', '0477473ba249ff440b2b731beaf3372c1bf86a7c', 'enc/streams.cc')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/nm6061/samaritan/services/.venv/lib/python3.7/site-packages/nameko/rpc.py", line 373, in __call__
    return reply.result()
  File "/home/nm6061/samaritan/services/.venv/lib/python3.7/site-packages/nameko/rpc.py", line 331, in result
    raise deserialize(error)
nameko.exceptions.RemoteError: IndexError list index out of range
```

**Comment by nuthanmunaiah** [comment]
In discussing this issue further, we decided to treat merge commits differently from regular commits. We decided to consider only those changes in a merge commit that the developer had to explicitly commit (for instance, in case of a merge conflict). The rationale for this decision is as follows.

In a typical `git` workflow, developers are often required to merge changes from other branches (remote or local). Let `master` be the target of such a merge commit and `development` be the source of the merge commit. Let `ad3d` be the SHA-1 of the commit at which the `development` branch split from `master`.

 * In cases when there is no overlap in the files modified in `master` and `development`, the developer merging the two branches must not be attributed with all the changes that are brought in by the merge. For instance, if a file `foo.c` was modified in or added to `master` and `bar.c` was modified in or added to `development`, merging `development` into `master` is merely bringing the changes to `bar.c` into `master`. In this case, the merge commit _must not be_ attributed with changes to `bar.c`.
 * In cases when there is an overlap in the files modified in `master` and `development`, the developer merging the two branches must be attributed with only those changes that overlap between the two branches. For instance, if a file `foo.c` was modified in both `master` and `development`, merging `development` into `master` _merges_ the changes to `foo.c` from `development` and `master` (with or without merge conflicts). In this case, the merge commit _must be_ attributed with the changes to `foo.c`.

## Examples

The following examples from https://github.com/google/brotli/ serve to illustrate the decision better.

 * https://github.com/google/brotli/commit/74147a1a41c21c1718bbac002f3f07aa6c70659e merged in changes to one file with no merge conflict. In this case, the merge commit `74147a1a41c21c1718bbac002f3f07aa6c70659e` itself it not attributable with having contributed any changes.
 * https://github.com/google/brotli/commit/4219fece592059522a1c800b3b16804d543f477e merged in changes to one file (`dec/port.h`) with a merge conflict. In this case, the merge commit `4219fece592059522a1c800b3b16804d543f477e` is attributable with having contributed the change that successfully merged the changes to `dec/port.h`.
 * https://github.com/google/brotli/commit/0477473ba249ff440b2b731beaf3372c1bf86a7c merged in changes to two files (`enc/streams.cc` and `enc/streams.h`) resolving a merge conflict in one of the two files (`enc/streams.cc`). In this case, the merge commit `0477473ba249ff440b2b731beaf3372c1bf86a7c` is only attributable with having contributed the change that successfully merge the changes to `enc/streams.cc` but not `enc/streams.h`.
